name: challenge2
on: push
env: 
  ARTIFACT_NAME: 'challenge2-artifact'
jobs:
  challenge2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout of the code
        uses: actions/checkout@v4
        with:
          repository: stella-0428/pythoncode
          ref: main
      - name: checkout of the code
        uses: actions/upload-artifact@v4
        with:
          name: $ARTIFACT_NAME
          path: artifact_storage/

    
    
