name: challenge2
on: push
env: 
  ARTIFACT_NAME: 'challenge2-artifact'
jobs:
  challenge2:
  runs-on: ubuntu-latest
  steps:
    - name: checkout of the code
      uses: actions/checkout@ref
        with:
          repository: stella-0428/python-code
          ref: main
    - name: checkout of the code
      uses: actions/upload-artifact
        with:
          name: $ARTIFACT_NAME
          path: artifacts_storage/

    
    
